repos:
  # -----------------------
  # BACKEND (Python)
  # -----------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix, --config=Backend/pyproject.toml]
        files: ^Backend/

      - id: ruff-format
        files: ^Backend/
        args: [--config=Backend/pyproject.toml]

  # -----------------------
  # FRONTEND (Angular)
  # -----------------------
  - repo: local
    hooks:
      - id: angular-eslint
        name: angular-eslint
        entry: bash -lc 'cd Frontend && pnpm exec eslint --fix "${@#Frontend/}"' --
        language: system
        types_or: [ts, html]
        files: ^Frontend/

  - repo: https://github.com/pre-commit/mirrors-prettier
    # Usamos una versión sólida y probada de la serie 3
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-frontend
        # Solo ejecuta en la carpeta Frontend
        files: ^Frontend/
        # Tipos de archivo
        types_or: [javascript, jsx, ts, tsx, css, scss, json, html, yaml]
        args:
          [
            '--cache-location=Frontend/node_modules/.cache/prettier/.prettiercache',
          ]
  # -----------------------
  # GENERAL (Todo el repo)
  # -----------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: 'Backend/alembic/versions/'
      - id: trailing-whitespace
        exclude: 'Backend/alembic/versions/'
      # # Evita commitear archivos con conflictos de merge sin resolver
      - id: check-merge-conflict
      - id: check-added-large-files
