services:
  app:
    build: ./Backend/
    container_name: echoparse-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    networks:
      - echoparse-network
  db:
    image: postgres:18.2-alpine3.22
    container_name: echoparse-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - echoparse-network

  cache:
    image: redis:7.4-alpine
    container_name: echoparse-cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - echoparse-network

volumes:
  postgres_data:
  redis_data:

networks:
  echoparse-network:
    driver: bridge
